title: The Research Software Engineer's Toolkit
description: >-
  The Research Software Engineer's Toolkit is a resource for RSEs, 
  researchers, academics and anyone involved with building or working
  with research software. It provides help and advice with technologies, 
  training and research credit as well as a command line tool for running
  or generating a variety of common processes or templates.
theme: jekyll-theme-slate
